destdir = '/tmp/icsmerge/dest'
destmode = 0o644
workdir = '/tmp/icsmerge/work'
maxsize = 0

[calendars.aqua]
url = 'https://club-aquarium.de/events/index.ics'

[calendars.baerenzwinter]
url = 'https://www.exmatrikulationsamt.de/downloads/schnusch/ics/baerenzwinger.ics'
processors = [
    { name = 'strip_emoji', args.properties = [ 'summary' ] },
]

[calendars.borsi]
url = 'https://www.exmatrikulationsamt.de/downloads/schnusch/ics/borsi.ics'

[calendars.club11]
url = 'https://cloud.clubelf.de/remote.php/dav/public-calendars/AbiNossEHEWpfC4d?export'
processors = [
    { name = 'add_default_property', args = { url = 'https://clubelf.de/kalender/', location = '''
Club 11 e.V.
Hochschulstraße 48
01069 Dresden''' } },
]

[calendars.countdown]
url = 'https://countdowndresden.de/events_/liste/?ical=1'

[calendars.gag18]
url = 'https://calendar.google.com/calendar/ical/kellerklubgag18@gmail.com/public/basic.ics'
processors = [
    { name = 'filter_out', args.summary.match = 'Nerd Out!|Büchertauschbörse|Spieleabend' },
    { name = 'add_default_property', args = { url = 'https://www.gag-18.com/veranstaltungen-1/veranstaltungskalender/', location = '''
Kellerklub GAG 18 e. V.
Fritz-Löffler-Str. 16
01069 Dresden''' } },
]

[calendars.gutzkowclub]
url = 'https://www.exmatrikulationsamt.de/downloads/schnusch/ics/gutzkowclub.ics'

[calendars.knm]
url = 'https://cloud.exma.de/remote.php/dav/public-calendars/sAbQMXGH5mmggQSk/?export'
processors = [
    { name = 'add_default_property', args.url = 'https://cloud.exma.de/apps/calendar/p/sAbQMXGH5mmggQSk' }
]

[calendars.'häma']
url = 'https://www.club-haengemathe.de/events.ics'

[calendars.novitatis]
url = 'https://www.exmatrikulationsamt.de/downloads/schnusch/ics/novitatis.ics'

[calendars.'traumtänzer']
url = 'https://www.exmatrikulationsamt.de/downloads/schnusch/ics/traumtaenzer.ics'
processors = [
    { name = 'filter_out', args.summary.match = 'Cocktailabend' },
]

[calendars.vdsc]
url = 'https://cloud.exma.de/remote.php/dav/public-calendars/y8dy2JPTFjKBy5Kg/?export'
processors = [
    { name = 'add_default_property', args.url = 'https://cloud.exma.de/apps/calendar/p/y8dy2JPTFjKBy5Kg' }
]

[calendars.wu5]
url = 'https://wu5.de/kalender.ics'
processors = [
    { name = 'filter_out', args.summary.match = 'Barabend.*|Termin.*' },
    { name = 'mod_uid', args.suffix = '@wu5.de' },
    { name = 'add_default_property', args = { url = 'https://wu5.de/kalender', location = '''
Studentenclub Wu5 e. V.
August-Bebel-Straße 12
01219 Dresden''' } },
    { name = 'strip_emoji', args.properties = [ 'summary' ] },
]
